#!/bin/bash -e

#export WEAVE_URL=${WEAVE_URL:="https://raw.githubusercontent.com/zettio/weave/master/weaver/weave"}

usage() {
cat <<EOF
Usage:
jencactl etcd
jencactl proxy
jencactl hyperkube
jencactl start
jencactl stop
jencactl help
EOF
	exit 1
}

# stop any container that the output of docker ps matches against the
# given grep pattern
grepstop-container() {
	local pattern=$1
	docker rm -f $(docker ps | grep $pattern | awk '{print $1}')
}

cmd-etcd() {
	docker run -d \
	  --name etcd \
	  --net host \
	  kubernetes/etcd:2.0.5.1 \
	  /usr/local/bin/etcd \
	  	--addr=127.0.0.1:4001 \
	  	--bind-addr=0.0.0.0:4001 \
	  	--data-dir=/var/etcd/data
}

cmd-hyperkube() {
	docker run -d \
		--net host \
		-v /var/run/docker.sock:/var/run/docker.sock \
		gcr.io/google_containers/hyperkube:v0.17.0 \
		/hyperkube kubelet \
			--api_servers=http://localhost:8080 \
			--v=2 \
			--address=0.0.0.0 \
			--enable_server \
			--hostname_override=127.0.0.1 \
			--config=/etc/kubernetes/manifests
}

cmd-proxy() {
	docker run -d \
		--net host \
		--privileged \
		gcr.io/google_containers/hyperkube:v0.17.0 \
		/hyperkube proxy \
			--master=http://127.0.0.1:8080 \
			--v=2
}

cmd-start() {
	cmd-etcd
	cmd-hyperkube
	cmd-proxy
}

cmd-stop() {
	grepstop-container k8s_scheduler
	grepstop-container k8s_apiserver
	grepstop-container k8s_controller-manager
	grepstop-container k8s_POD
	grepstop-container kubelet
	grepstop-container etcd	
	#docker rm -f INSERTNAMESHERE
}

main() {
	case "$1" in
	etcd)					        shift; cmd-etcd; $@;;
	hyperkube)					  shift; cmd-hyperkube; $@;;
	proxy)					      shift; cmd-proxy; $@;;
	start)					      shift; cmd-start; $@;;
	stop)					        shift; cmd-stop; $@;;
	*)                    usage $@;;
	esac
}

main "$@"
